[package]
name = "uni"
version = "0.4.0"
edition = "2021"

[profile.release]
strip = true

[dependencies]
copypasta = "0.10.1"
pop-launcher = "1.1.0"
serde = "1.0.210"
serde_json = "1.0.128"
strsim = "0.11.1"
