name: Create the DEB

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  Create_Packages:
    name: Create Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Build the package
        run: |
          apt install debmake
          debmake -p pop-launcher-plugin-uni -t
          debuild -us -uc

      - name: Release the Package
        uses: softprops/action-gh-release@v1
        with:
          files: pop-launcher-plugin-uni*.deb
